document.addEventListener('DOMContentLoaded',()=>{
'use strict';
const body=document.body,header=document.getElementById('siteHeader'),menu=document.getElementById('menuToggle'),nav=document.getElementById('navLinks'),audio=document.getElementById('radioAudio'),play=document.getElementById('radioPlay'),status=document.getElementById('radioStatus'),message=document.getElementById('radioMessage'),volume=document.getElementById('radioVolume');
const stream='https://stream.zeno.fm/amfjjcz4tlgtv',whatsapp='542996728355',reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* Sistema visual complementario */
const css=document.createElement('style');css.textContent=`
.audiences{background:#fff}.audiences:before,.services:before,.productions:before{content:"";display:block;width:48px;height:2px;background:var(--accent);margin-bottom:24px}
.audience-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;background:var(--line)}.audience-grid article{background:#f7f4ed;min-height:190px;padding:25px;display:flex;flex-direction:column;justify-content:space-between;transition:.25s}.audience-grid article:hover{background:#fff;transform:translateY(-3px)}.audience-grid b{font-size:.62rem;color:var(--accent);letter-spacing:.14em}.audience-grid h3{margin:20px 0 0;font-size:1.35rem;line-height:1}.audience-grid p{margin:8px 0 0;color:var(--muted);font-size:.9rem;line-height:1.55}
.process{position:relative}.process .section-head{margin-bottom:50px}.process-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:rgba(255,255,255,.12)}.process-grid article{min-height:250px;padding:28px;background:var(--dark-2);display:flex;flex-direction:column;justify-content:space-between}.process-grid span{font-size:.65rem;color:var(--accent);letter-spacing:.14em}.process-grid h3{font-size:1.8rem;margin:25px 0 0}.process-grid p{color:rgba(255,255,255,.56);line-height:1.65;margin:8px 0 0}
.mid-cta{margin-top:70px;padding:28px 0;border-top:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:25px}.mid-cta span{font-size:.8rem;color:var(--muted)}.service-card,.audience-grid article,.process-grid article,.universe-card,.work-card{min-width:0}.work-card{overflow:hidden}.mid-cta .button{white-space:nowrap}
.contact-inner{max-width:980px}.inquiry{margin-top:48px;padding:32px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.14);text-align:left}.inquiry-head{display:flex;justify-content:space-between;align-items:end;gap:25px;margin-bottom:25px}.inquiry-head h3{margin:0;font-size:1.5rem}.inquiry-head p{margin:5px 0 0;color:rgba(255,255,255,.58);font-size:.88rem}.inquiry-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.inquiry-field{display:flex;flex-direction:column;gap:7px}.inquiry-field.full{grid-column:1/-1}.inquiry label{font-size:.68rem;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.62)}.inquiry input,.inquiry select,.inquiry textarea{width:100%;box-sizing:border-box;border:1px solid rgba(255,255,255,.16);background:#10171b;color:#fff;border-radius:0;padding:13px 14px;font:inherit;outline:none}.inquiry input:focus,.inquiry select:focus,.inquiry textarea:focus{border-color:var(--accent);box-shadow:0 0 0 2px rgba(200,157,88,.12)}.inquiry textarea{min-height:115px;resize:vertical}.inquiry select{appearance:auto}.inquiry-note{font-size:.78rem!important;color:rgba(255,255,255,.48)!important;margin:14px 0 0!important}.inquiry-result{margin:15px 0 0;color:var(--accent);font-size:.8rem;min-height:1.2em}.inquiry-submit{margin-top:18px}
@media(max-width:950px){.audience-grid,.process-grid{grid-template-columns:1fr 1fr}.mid-cta{margin-top:55px}}
@media(max-width:620px){.audience-grid,.process-grid,.inquiry-grid{grid-template-columns:1fr}.audience-grid article{min-height:170px}.process-grid article{min-height:220px}.mid-cta{align-items:flex-start;flex-direction:column}.mid-cta .button{width:100%;white-space:normal}.inquiry{padding:22px}.inquiry-head{display:block}.inquiry-head h3{font-size:1.25rem}.inquiry-field.full{grid-column:auto}.inquiry-submit{width:100%}}
`;document.head.appendChild(css);

/* Navegación */
const updateHeader=()=>header?.classList.toggle('scrolled',window.scrollY>35);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
const closeMenu=()=>{nav?.classList.remove('active');menu?.classList.remove('active');menu?.setAttribute('aria-expanded','false');body.classList.remove('no-scroll')};
menu?.addEventListener('click',()=>{const open=nav?.classList.toggle('active');menu.classList.toggle('active',open);menu.setAttribute('aria-expanded',String(!!open));body.classList.toggle('no-scroll',!!open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href'),target=id&&document.querySelector(id);if(!target)return;e.preventDefault();window.scrollTo({top:Math.max(0,target.getBoundingClientRect().top+window.scrollY-(header?.offsetHeight||0)-10),behavior:reduced?'auto':'smooth'})}));

/* Animaciones */
const reveal=document.querySelectorAll('.statement-grid,.section-head,.service-card,.audience-grid article,.process-grid article,.universe-card,.work-card,.territory-inner,.archive-grid,.radio-grid,.club-grid,.contact-inner,.mid-cta');reveal.forEach(el=>el.classList.add('reveal'));if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -35px 0px'});reveal.forEach(el=>observer.observe(el))}else reveal.forEach(el=>el.classList.add('visible'));

/* Radio */
const setRadio=state=>{const s={ready:['OCARINA RADIO · LISTO','Presioná reproducir para escuchar.','▶'],connecting:['OCARINA RADIO · CONECTANDO','Conectando con la transmisión…','■'],playing:['OCARINA RADIO · EN VIVO','Transmisión en directo.','❚❚'],paused:['OCARINA RADIO · PAUSADA','La transmisión está pausada.','▶'],error:['OCARINA RADIO · SIN SEÑAL','No fue posible conectar con la transmisión.','▶']}[state]||[];if(status)status.textContent=s[0];if(message)message.textContent=s[1];if(play){play.textContent=s[2];play.setAttribute('aria-label',state==='playing'?'Pausar Ocarina Radio':'Reproducir Ocarina Radio')}};
let initialized=false;const initRadio=()=>{if(initialized||!audio)return;audio.src=stream;audio.preload='none';audio.volume=Number(volume?.value)||.8;initialized=true};const start=async()=>{if(!audio)return;initRadio();setRadio('connecting');try{await audio.play()}catch(err){console.warn('Ocarina Radio:',err);setRadio('error')}};play?.addEventListener('click',()=>audio?.paused?start():audio.pause());volume?.addEventListener('input',()=>{if(audio)audio.volume=Number(volume.value)});audio?.addEventListener('playing',()=>setRadio('playing'));audio?.addEventListener('waiting',()=>setRadio('connecting'));audio?.addEventListener('pause',()=>setRadio('paused'));audio?.addEventListener('error',()=>setRadio('error'));setRadio('ready');

/* Formulario de orientación comercial: sin backend, sin guardar datos */
const contact=document.getElementById('contacto');
if(contact&&!contact.querySelector('#inquiryForm')){
const form=document.createElement('form');form.id='inquiryForm';form.className='inquiry';form.innerHTML=`<div class="inquiry-head"><div><h3>Contanos qué necesitás</h3><p>No hace falta que tengas el proyecto resuelto.</p></div></div><div class="inquiry-grid"><div class="inquiry-field"><label for="inqName">Nombre</label><input id="inqName" name="name" autocomplete="name" required placeholder="Tu nombre"></div><div class="inquiry-field"><label for="inqContact">Cómo te contactamos</label><input id="inqContact" name="contact" required placeholder="WhatsApp, email o ambos"></div><div class="inquiry-field"><label for="inqService">Qué necesitás</label><select id="inqService" name="service" required><option value="" selected disabled>Elegí una opción</option><option>Producción audiovisual</option><option>Fotografía</option><option>Comunicación</option><option>Historias & memoria</option><option>Territorio & turismo</option><option>Contenidos digitales</option><option>Otro / todavía no lo sé</option></select></div><div class="inquiry-field"><label for="inqType">Tipo de proyecto</label><input id="inqType" name="type" placeholder="Ej. emprendimiento, evento, historia, institución…"></div><div class="inquiry-field full"><label for="inqObjective">Qué querés lograr</label><textarea id="inqObjective" name="objective" required placeholder="Contanos brevemente qué querés comunicar, registrar o resolver."></textarea></div><div class="inquiry-field"><label for="inqLocation">Dónde sería</label><input id="inqLocation" name="location" placeholder="Localidad / lugar"></div><div class="inquiry-field"><label for="inqTiming">Cuándo</label><input id="inqTiming" name="timing" placeholder="Fecha aproximada o sin definir"></div></div><p class="inquiry-note">Al enviar, se abre WhatsApp con la información que escribiste. Ocarina no guarda este formulario.</p><button class="button button-primary inquiry-submit" type="submit">Preparar consulta por WhatsApp →</button><p class="inquiry-result" id="inquiryResult" aria-live="polite"></p>`;
contact.querySelector('.contact-actions')?.insertAdjacentElement('afterend',form);
form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),v=k=>String(data.get(k)||'').trim();const name=v('name'),contactInfo=v('contact'),service=v('service'),type=v('type'),objective=v('objective'),location=v('location'),timing=v('timing');const lines=[`Hola Ocarina. Soy ${name}.`,``,`Me interesa: ${service}.`,type?`Proyecto: ${type}.`:null,`Objetivo: ${objective}.`,location?`Ubicación: ${location}.`:null,timing?`Plazo: ${timing}.`:null,`Mi contacto: ${contactInfo}.`].filter(Boolean);const url=`https://wa.me/${whatsapp}?text=${encodeURIComponent(lines.join('\n'))}`;const result=document.getElementById('inquiryResult');if(result)result.textContent='Abriendo WhatsApp con tu consulta…';window.open(url,'_blank','noopener,noreferrer')});
}

/* Datos estructurados para buscadores */
if(!document.querySelector('script[data-ocarina-schema]')){const schema=document.createElement('script');schema.type='application/ld+json';schema.dataset.ocarinaSchema='true';schema.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Organization","name":"Ocarina Producciones","url":"https://eliasmartinezcultural-glitch.github.io/ocarina-producciones/","description":"Producción audiovisual, fotografía y comunicación con mirada territorial desde San Patricio del Chañar, Neuquén.","email":"eliasmartinezcultural@gmail.com","telephone":"+54 299 672 8355","areaServed":["San Patricio del Chañar","Neuquén","Patagonia"],"founder":{"@type":"Person","name":"Elías Martínez"}});document.head.appendChild(schema)}

const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
});