document.addEventListener('DOMContentLoaded',()=>{
'use strict';
const body=document.body,header=document.getElementById('siteHeader'),menu=document.getElementById('menuToggle'),nav=document.getElementById('navLinks');
const audio=document.getElementById('radioAudio'),play=document.getElementById('radioPlay'),status=document.getElementById('radioStatus'),message=document.getElementById('radioMessage'),volume=document.getElementById('radioVolume');
const stream='https://stream.zeno.fm/amfjjcz4tlgtv',whatsapp='542996728355',reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const updateHeader=()=>header?.classList.toggle('scrolled',window.scrollY>35);
updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
const closeMenu=()=>{nav?.classList.remove('active');menu?.classList.remove('active');menu?.setAttribute('aria-expanded','false');body.classList.remove('no-scroll')};
menu?.addEventListener('click',()=>{const open=!nav.classList.contains('active');nav.classList.toggle('active',open);menu.classList.toggle('active',open);menu.setAttribute('aria-expanded',String(open));body.classList.toggle('no-scroll',open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});

document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href'),target=id&&document.querySelector(id);if(!target)return;e.preventDefault();window.scrollTo({top:Math.max(0,target.getBoundingClientRect().top+window.scrollY-(header?.offsetHeight||0)-8),behavior:reduced?'auto':'smooth'})}));

const reveal=document.querySelectorAll('.statement-grid,.section-head,.service-card,.fit-grid article,.method-grid article,.universe-card,.work-card,.territory-inner,.credentials-grid,.archive-grid,.radio-grid,.club-grid,.faq-list,.contact-inner,.portfolio-cta,.trust-grid');
reveal.forEach((el,i)=>{el.classList.add('reveal');el.style.transitionDelay=`${Math.min(i%6,5)*55}ms`});
if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.07,rootMargin:'0px 0px -30px 0px'});reveal.forEach(el=>observer.observe(el))}else reveal.forEach(el=>el.classList.add('visible'));

const setRadio=state=>{const states={ready:['OCARINA RADIO · LISTO','Presioná reproducir para escuchar.','▶'],connecting:['OCARINA RADIO · CONECTANDO','Conectando con la transmisión…','■'],playing:['OCARINA RADIO · EN VIVO','Transmisión en directo.','❚❚'],paused:['OCARINA RADIO · PAUSADA','La transmisión está pausada.','▶'],error:['OCARINA RADIO · SIN SEÑAL','No fue posible conectar con la transmisión.','▶']};const s=states[state]||states.ready;if(status)status.textContent=s[0];if(message)message.textContent=s[1];if(play){play.textContent=s[2];play.setAttribute('aria-label',state==='playing'?'Pausar Ocarina Radio':'Reproducir Ocarina Radio')}};
let radioReady=false;const initRadio=()=>{if(radioReady||!audio)return;audio.src=stream;audio.preload='none';audio.volume=Number(volume?.value)||.8;radioReady=true};
const startRadio=async()=>{if(!audio)return;initRadio();setRadio('connecting');try{await audio.play()}catch(err){console.warn('Ocarina Radio:',err);setRadio('error')}};
play?.addEventListener('click',()=>audio?.paused?startRadio():audio.pause());volume?.addEventListener('input',()=>{if(audio)audio.volume=Number(volume.value)});audio?.addEventListener('playing',()=>setRadio('playing'));audio?.addEventListener('waiting',()=>setRadio('connecting'));audio?.addEventListener('pause',()=>setRadio('paused'));audio?.addEventListener('error',()=>setRadio('error'));setRadio('ready');

const contact=document.getElementById('contacto');
if(contact&&!contact.querySelector('#inquiryForm')){
const style=document.createElement('style');style.textContent=`#inquiryForm{margin-top:48px;padding:28px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.13);text-align:left}#inquiryForm .inquiry-head{margin-bottom:22px}#inquiryForm h3{margin:0;font-size:1.4rem}#inquiryForm .inquiry-sub{margin:5px 0 0!important;font-size:.8rem!important;color:rgba(255,255,255,.48)!important}.inquiry-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.inquiry-field{display:flex;flex-direction:column;gap:7px}.inquiry-field.full{grid-column:1/-1}.inquiry-field label{font-size:.61rem;letter-spacing:.11em;text-transform:uppercase;color:rgba(255,255,255,.58)}.inquiry-field input,.inquiry-field select,.inquiry-field textarea{width:100%;border:1px solid rgba(255,255,255,.15);border-radius:0;background:#10171b;color:#fff;padding:12px 13px;outline:0}.inquiry-field textarea{min-height:105px;resize:vertical}.inquiry-field input:focus,.inquiry-field select:focus,.inquiry-field textarea:focus{border-color:var(--accent)}.inquiry-note{margin:12px 0 0!important;font-size:.68rem!important;color:rgba(255,255,255,.4)!important}.inquiry-submit{margin-top:16px}@media(max-width:640px){#inquiryForm{padding:20px}.inquiry-grid{grid-template-columns:1fr}.inquiry-field.full{grid-column:auto}.inquiry-submit{width:100%}}`;document.head.appendChild(style);
const form=document.createElement('form');form.id='inquiryForm';form.innerHTML=`<div class="inquiry-head"><h3>Contanos qué necesitás</h3><p class="inquiry-sub">Si todavía no sabés exactamente qué formato necesitás, está bien.</p></div><div class="inquiry-grid"><div class="inquiry-field"><label for="inqName">Nombre</label><input id="inqName" name="name" autocomplete="name" required placeholder="Tu nombre"></div><div class="inquiry-field"><label for="inqContact">Contacto</label><input id="inqContact" name="contact" required placeholder="WhatsApp o email"></div><div class="inquiry-field"><label for="inqService">Necesidad</label><select id="inqService" name="service" required><option value="" selected disabled>Elegí una opción</option><option>Producción audiovisual</option><option>Fotografía</option><option>Comunicación</option><option>Historias & memoria</option><option>Territorio & turismo</option><option>Contenidos digitales</option><option>Otro / todavía no lo sé</option></select></div><div class="inquiry-field"><label for="inqTiming">Cuándo</label><input id="inqTiming" name="timing" placeholder="Fecha aproximada o sin definir"></div><div class="inquiry-field full"><label for="inqObjective">Qué querés lograr</label><textarea id="inqObjective" name="objective" required placeholder="Contanos brevemente la idea, necesidad o proyecto."></textarea></div></div><p class="inquiry-note">Al enviar, se abre WhatsApp con tu consulta. Ocarina no guarda este formulario.</p><button class="button button-primary inquiry-submit" type="submit">Preparar consulta →</button>`;
contact.querySelector('.contact-actions')?.insertAdjacentElement('afterend',form);
form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),v=k=>String(data.get(k)||'').trim();const text=[`Hola Ocarina. Soy ${v('name')}.`,``,`Necesito: ${v('service')}.`,`Objetivo: ${v('objective')}.`,v('timing')?`Cuándo: ${v('timing')}.`:null,`Mi contacto: ${v('contact')}.`].filter(Boolean).join('\n');window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')});
}

if(!document.querySelector('script[data-ocarina-schema]')){const schema=document.createElement('script');schema.type='application/ld+json';schema.dataset.ocarinaSchema='true';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Organization','name':'Ocarina Producciones','url':'https://eliasmartinezcultural-glitch.github.io/ocarina-producciones/','description':'Producción audiovisual, fotografía y comunicación con mirada territorial desde San Patricio del Chañar, Neuquén.','email':'eliasmartinezcultural@gmail.com','telephone':'+54 299 672 8355','areaServed':['San Patricio del Chañar','Neuquén','Patagonia'],'founder':{'@type':'Person','name':'Elías Martínez'}});document.head.appendChild(schema)}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
});
